# Generated by Django 3.2.12 on 2022-07-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='info',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
